### ISSUE TITLE
The config Dino view service wiki link points to subject area

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3709] opened 2020-09-29 17:36 UTC
When querying the view service config for dino I get:
```
          {
                "class": "ViewServiceConfig",
                "viewServiceAdminClass": "org.odpi.openmetadata.viewservices.dino.admin.DinoViewAdmin",
                "viewServiceDescription": "Operate an open metadata topology.",
                "viewServiceFullName": "Dino OMVS",
                "viewServiceId": 1040,
                "viewServiceName": "Dino",
                "viewServiceOperationalStatus": "ENABLED",
                "viewServiceURLMarker": "dino",
                "viewServiceWiki": "https://odpi.github.io/egeria/open-metadata-implementation/access-services/subject-area/"
            }
```

The Wiki should be updated to link to dino

**Comment by mandy-chessell** [comment] 2020-09-30 07:21
I fixed that yesterday when fixing merge conflicts - its in my PR.

**Comment by grahamwallis** [comment] 2020-09-30 13:19
I think you'll find Rex and Tex are similar - the problem is there are no wikis, so this was a placeholder really....

**Comment by mandy-chessell** [comment] 2020-09-30 21:11
I have fixed REX and TEX so they have readme pages and the links are ok.
I have also changed DINO's component identifier because it was using Subject Area OMAS's number and moved error messages used by Dino into Dino's errorcode list - they were in OMAGCommon which is not correct.  There was no other impact on this change because no other module was using them.

**Comment by grahamwallis** [comment] 2020-10-02 11:04
Many thanks @planetf1 and @mandy-chessell. Is there anything else that needs doing to complete this - sounds like you have mailed it already.

**Comment by planetf1** [comment] 2020-10-02 11:05
Looks good, though note this will not be in 2.3

**Comment by grahamwallis** [comment] 2020-10-02 11:10
I don't think this is urgent enough for 2.3

**Comment by grahamwallis** [comment] 2020-10-09 16:09
Fixed in master

**Closed by grahamwallis** 2020-10-09 16:09 UTC
