### ISSUE TITLE
Review SIGINT handling - User system is not authorised

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2020] opened 2019-11-18 12:56 UTC
When shutting down a series of egeria servers using CTRL-C (SIGINT) the following messages are observed:
```
Context closed received. Temporary deactivating servers
Context closed received. Temporary deactivating servers
Mon Nov 18 12:48:23 GMT 2019 cocoMDS1 Security OPEN-METADATA-SECURITY-0006 User system is not authorized to issue a request to server cocoMDS1
Mon Nov 18 12:48:23 GMT 2019 cocoMDS2 Security OPEN-METADATA-SECURITY-0006 User system is not authorized to issue a request to server cocoMDS2
Mon Nov 18 12:48:23 GMT 2019 cocoMDS3 Security OPEN-METADATA-SECURITY-0006 User system is not authorized to issue a request to server cocoMDS3
Mon Nov 18 12:48:23 GMT 2019 cocoMDS4 Security OPEN-METADATA-SECURITY-0006 User system is not authorized to issue a request to server cocoMDS4
```
The server's do shutdown - or at least the processes do terminate

We might be able to / wish to do something with java.lang.Runtime.addShutdownHook to refine the handling of SIGHUP/SIGINT/SIGTERM - though note behaviour may differ between JVMs as well as platforms.

The 'not authorized' error may indicate there's some cleaning up we should do that we're skipping - ultimately if the process itself receives such a signal, the invoking user is privileged at a system level to terminate the process, so not authorised isn't that helpful (though a dedicated message indicating an unexpected shutdown could be valid if we want to suggest other mechanisms to shut down).

In a highly available cluster environment one can expect our containers (OS and hence process) to be terminated regularly as resources are rebalanced/reconfigured - in this case the process probably gets a SIGTERM

**Comment by mandy-chessell** [comment] 2019-11-18 13:21
This is a duplicate of #1878

**Comment by planetf1** [comment] 2019-11-18 15:33
Ok can close - the referenced issue didn't document the text being put out so it wasn't clear it was the same.

**Closed** 2019-11-18 15:33 UTC
