### ISSUE TITLE
[BUG] Unable to attach Connection to DataAsset

### ISSUE THREAD

**Issue by alex231330** [odpi/egeria#5945] opened 2021-11-24 05:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to create a connection between DataAsset and Connection again. The old bug (https://lfaifoundation.slack.com/archives/C01F40J2XA8/p1635499905058100) is gone now, but there is a new one. 

### Expected Behavior

As sure i expect a successful result

### Steps To Reproduce

So, the request:

`curl -X 'POST' \
  '{serverUrl}/servers/{serverName}/open-metadata/access-services/asset-owner/users/{username}/assets/15f73d79-5e62-40fe-be4e-87723548d761/connections/b9bfaf2c-d365-494f-9b7a-78ebc118c4d9' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "class": "AssetElementResponse",
  "relatedHTTPCode": 200,
  "asset": {
    "elementHeader": {
      "guid": "15f73d79-5e62-40fe-be4e-87723548d761",
      "type": {
        "typeId": "8078e3d1-0c63-4ace-aafa-68498b39ccd6",
        "typeName": "Form",
        "superTypeNames": [
          "DataSet",
          "Asset",
          "Referenceable",
          "OpenMetadataRoot"
        ],
        "typeVersion": 1,
        "typeDescription": "A collection of data items used to request activity."
      },
      "origin": {
        "sourceServer": "{serverName}",
        "originCategory": "LOCAL_COHORT",
        "homeMetadataCollectionId": "81c1b8e5-c6c8-49eb-8eb3-53944a8c622f",
        "homeMetadataCollectionName": "{serverName}"
      }
    },
    "assetProperties": {
      "class": "AssetProperties",
      "qualifiedName": "name",
      "typeName": "Form",
      "ownerType": "OTHER"
    }
  }
}'`

And the result:

`{
  "timestamp": "2021-11-23T08:36:25.204+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "message": "'boolean org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.typedefs.RelationshipDef.getMultiLink()'",
  "path": "/servers/paukd-platform-rnd/open-metadata/access-services/asset-owner/users/admin/assets/15f73d79-5e62-40fe-be4e-87723548d761/connections/b9bfaf2c-d365-494f-9b7a-78ebc118c4d9"
}`

### Environment

```markdown
- Egeria: 3.4 Snapshot 
- OS: Windows 10
- Java: 16 adoptopenjdk
- Browser (for UI issues): Chrome 
- Additional connectors and integration: None
```

**Comment by mandy-chessell** [comment] 2021-12-03 08:21
The response is status 500.  This suggests it was returned by Spring not by Egeria (which always returns status 200 with the error in the response body).  If this is the case then the REST request is inconsistent with the server definition.

It is suspicious that a response class of AssetElementResponse is being passed  as a request body (ie -d option) which should be StringRequestBody.  I suspect that is the cause of the problem.

**Comment by mandy-chessell** [comment] 2021-12-10 10:43
@alex231330 any feedback on this?

**Comment by planetf1** [comment] 2021-12-13 13:41
This looks as if it's the API response to a system behaving as per https://github.com/odpi/egeria/issues/6020 - where an exception occurred due to a method not being found, suspected mixed 3.4 & lower version jars...

**Comment by planetf1** [comment] 2022-01-25 16:16
I think this was caused by a strange setup. Closing, but please re-open if still an issue

**Closed by planetf1** 2022-01-25 16:16 UTC
Labels: bug, triage
