### ISSUE TITLE
Restart KafkaOpenMetadataEventConsumer if thread dies

### ISSUE THREAD

**Issue by Surajdivate** [odpi/egeria#5502] opened 2021-07-24 13:45 UTC
We have been having problems where, for whatever reason the KafkaOpenMetadataEventConsumer thread dies. When this happens, the sync processing completely stops. In order for our product to continue functioning when this happens, we need the KafkaOpenMetadataEventConsumer thread to be restarted if it dies.

There is already similar logic for restarting the KafkaOpenMetadataEventProducer if that thread dies. The mechanism needs to be extended to also apply to the consumer.

**Comment by planetf1** [comment] 2021-07-26 13:33
@Surajdivate Closing as a duplicate of #5407

**Closed by planetf1** 2021-07-26 13:33 UTC
