### ISSUE TITLE
Release 1.7 - AssetManagement notebook - fails on addCommentToAsset

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3005] opened 2020-04-30 13:50 UTC
Testing release 1.7 ( 632e6e1a6ece21ec9f1fd8607249f5adc31b33d8 )

The 'building a data catalog' notebook fails in step 10 when Erin adds a comment to the asset - this fails with:
```
No comment added
OMAG-REPOSITORY-HANDLER-404-007 The Asset with unique identifier 2f04e58e-a166-4d24-af60-1c066401fad0 is not found for method addCommentToAsset of access service Asset Consumer OMAS in open metadata server cocoMDS2, error message was: OMRS-REPOSITORY-404-002 The entity identified with guid 2f04e58e-a166-4d24-af60-1c066401fad0 passed on the getEntitySummary call is not known to the open metadata repository cocoMDS5
 * The system is unable to update information associated with the asset because none of the connected open metadata repositories recognize the asset's unique identifier.
 * The unique identifier of the asset is supplied by the caller.  Verify that the caller's logic is correct, and that there are no errors being reported by the open metadata repository. Once all errors have been resolved, retry the request.
 ```

The asset mentioned in one that Peter created in the previous step.

There are consequential errors then in further steps

In addition trying to retrieve the comments in step 11 also fails to find the original entity (of course no comment as it failed above).

**Comment by planetf1** [comment] 2020-04-30 14:00
For adding to the release notes - 
 * https://github.com/odpi/egeria/issues/2935 - 'Exception OMAS-GOVERNANCE-ENGINE-0008 The Governance Engine Open Metadata Access Service (OMAS) encounter an exception while processing incoming event {0}' is being reported constantly when dealing with entities

**Comment by planetf1** [comment] 2020-04-30 14:45
This looks like an intermittent (probably timing-related issue). 
I think you saw this @mandy-chessell  ? (it's different to the window I saw before)

**Comment by mandy-chessell** [comment] 2020-04-30 15:31
This is a different problem unfortunately

**Comment by mandy-chessell** [comment] 2020-05-15 13:49
Seems to be duplicate of #2688?

**Comment by planetf1** [comment] 2020-05-15 15:38
Probably. Needs re-testing with a log captured... SHall we close this as dup and persue in the other one?

**Comment by mandy-chessell** [comment] 2020-05-15 15:44
I think so - as long as they are linked we can get back to this one

**Closed** 2020-05-15 17:03 UTC
Labels: bug, release
