### ISSUE TITLE
Egeria container 2.0-SNAPSHOT fails to start

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria#3211] opened 2020-06-16 23:38 UTC
Command `docker run --rm --name egeria odpi/egeria:2.0-SNAPSHOT` used to work. Now it fails with error below. (helm chart deployment shows the same error)
```Zorans-MacBook-Pro:egeria zoran@ibm.com$ docker run --rm --name egeria odpi/egeria:2.0-SNAPSHOT
Unable to find image 'odpi/egeria:2.0-SNAPSHOT' locally
2.0-SNAPSHOT: Pulling from odpi/egeria
e7c96db7181b: Already exists
f910a506b6cb: Already exists
b6abafe80f63: Already exists
09a8069128db: Pull complete
232358073cb3: Pull complete
c520c5cc6b82: Pull complete
Digest: sha256:e1369d43065c1f3eab12c25aa1b8496f472ec836777e9ae5209176220a616ff5
Status: Downloaded newer image for odpi/egeria:2.0-SNAPSHOT
Picked up JAVA_TOOL_OPTIONS:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/egeria/server/lib/graph-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/egeria/server/lib/open-lineage-janus-connector-2.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/egeria/server/server-chassis-spring-2.0-SNAPSHOT.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.3.1.RELEASE) ::

23:26:11.632 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9443 (https)
23:26:17.677 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter -

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraDriverConfigLoader(CassandraAutoConfiguration.java:111)

The following method did not exist:

    com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder.<init>(Ljava/util/function/Supplier;Ljava/lang/String;)V

The method's class, com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder, is available from the following locations:

    jar:file:/opt/egeria/server/lib/cassandra-data-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar!/com/datastax/oss/driver/internal/core/config/typesafe/DefaultProgrammaticDriverConfigLoaderBuilder.class
    jar:file:/opt/egeria/server/lib/cassandra-metadata-extractor-connector-2.0-SNAPSHOT-jar-with-dependencies.jar!/com/datastax/oss/driver/internal/core/config/typesafe/DefaultProgrammaticDriverConfigLoaderBuilder.class

The class hierarchy was loaded from the following locations:

    com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder: file:/opt/egeria/server/lib/cassandra-data-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder```

**Comment by planetf1** [comment] 2020-06-17 07:47
will take a look

**Comment by planetf1** [comment] 2020-06-17 08:56
I can confirm this critical  error.

We are moving towards the point where we will not load these optional connectors every time the server is launched, and one step towards that was #3101

#3204 is the cause of the SLF warnings - but this shouldn't have a big impact

**Comment by planetf1** [comment] 2020-06-17 09:22
The server chassis does load correctly
 - when run from the server chassis target directory
 - when run from the assembly.

In the latter case both the cassandra connectors listed are present in lib - and hence the classpath

**Comment by planetf1** [comment] 2020-06-17 09:27
We have a couple of components currently being brought in that tend to bring in a non trivial dependency set - these include JanusGraph, Cassandra, hadoop 

The error above is relating to some inconsistency in the cassandra libraries - though the changes I mentioned above result in two copies (as expected) they are of the same version and neither seems correct... here we can find the class, but not the required method
```
com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder.<init>(Ljava/util/function/Supplier;Ljava/lang/String;)V
```

**Comment by planetf1** [comment] 2020-06-17 09:33
What is odd, is that in the container we literally have the unpacked assembly (which works locally) and then launch the chassis. Without compose/k8s no significant environment variables are set. (even when LOADER_PATH is set locally)

**Comment by planetf1** [comment] 2020-06-17 09:38
It's possible this dependency update is to blame -> https://github.com/odpi/egeria/commit/2c64826192cbf2f122a70c967148b66d37126f7b

**Comment by planetf1** [comment] 2020-06-17 10:09
Rebuilt without the update to java-driver-core from cassandra, and problem no longer occurs.

Looks like a bad update or exposing an incompatability with other cassandra libraries.

This reenforces one good reason for implementing dynamically loaded connectors - we can control behaviour better and not fail all function if just one component is broken (which most people aren't using)

**Closed** 2020-06-17 10:47 UTC
Labels: bug

**Comment by planetf1** [comment] 2020-06-17 10:49
As soon as https://dev.azure.com/ODPi/Egeria/_build/results?buildId=7962&view=results completes, ensure you re-pull the docker image and it should work correctly.

I'll do a final test (was ok locally) on the merged build once done also. 

Thanks for spotting.

**Comment by planetf1** [comment] 2020-06-17 11:19
I've raised an issue with datastax at https://datastax-oss.atlassian.net/browse/JAVA-2817 - it won't be visible yet until they've reviewed, but will try and determine if this is
 a) a regression in the datastax driver
 b) An issue with spring compatability
 c) out code

I suspect a or b....

cc: @DimitriosMaimaris @mstrelchuk do we have a replacement codeowner for @cong78 on cassandra related code?

**Comment by planetf1** [comment] 2020-06-17 11:22
Docker image looks good now:
```
jonesn:egeria/ (master) $ jonesn:egeria/ (master) $ docker run 02ce322c96cc                                                                                          [11:42:17]
Picked up JAVA_TOOL_OPTIONS:
 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.3.1.RELEASE) ::

10:43:41.268 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9443
jonesn:egeria/ (master) $ docker run odpi/egeria:latest                                                                                    [12:12:43]
Unable to find image 'odpi/egeria:latest' locally
latest: Pulling from odpi/egeria
e7c96db7181b: Already exists
f910a506b6cb: Already exists
b6abafe80f63: Already exists
fa2e4a9af08e: Pull complete
6cb08eb50b24: Pull complete
e8b23e06375e: Pull complete
Digest: sha256:2e590aa54cb379cff8864761c422a6ebdc04f08bbfc328a4a8b6db13686c1501
Status: Downloaded newer image for odpi/egeria:latest
Picked up JAVA_TOOL_OPTIONS:
 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.3.1.RELEASE) ::

11:21:33.750 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9443 (https)
11:21:43.233 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 9443 (https) with context path ''

Wed Jun 17 11:21:35 GMT 2020 No OMAG servers listed in startup configuration
Wed Jun 17 11:21:43 GMT 2020 OMAG server platform ready for more configuration
```

**Comment by planetf1** [comment] 2020-06-17 11:25
A very quick update from the datastax team:

```

Alexandre Dutra 4:17 AM PDT
--
Hi, indeed driver 4.7.0 changes the signature of an internal API and Spring Boot relies on that. We are going to provide a fix to Spring Boot shortly, but in the meantime please do not upgrade to 4.7.0.


```
Looks like we'll just skip this minor update

**Comment by planetf1** [comment] 2020-06-18 14:16
The 4.7.1 driver is now available & fixes the reported issue (quick work from the cassandra driver team) - so we'll look at integrating once dependabot picks it up
