### ISSUE TITLE
[BUG] data-files engine is eventually inconsistent

### ISSUE THREAD

**Issue by djohn156** [odpi/egeria#5854] opened 2021-10-28 12:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When inserting files using the data-engine's data-files endpoint, the resolution of path names seems to fail eventually. 
The issue appears when I
1. Register a data engine
2. Add some data-files to that engine
3. Remove the engine
4. Register the same engine
5. Add the same files again

While after step (2), file paths are associated consistently across the different files
![image](https://user-images.githubusercontent.com/20514614/139252812-ae94447f-9653-4d15-9338-fa6a740e1962.png)
after step (5) the path names are not always resolved correctly (in this particular example, `example1.dat` was not resolved correctly as it cannot be found by exploring its parent node).
![image](https://user-images.githubusercontent.com/20514614/139253760-e3e77ce0-a449-4829-a910-a869b3a08d69.png)

### Expected Behavior

After deleting a data-engine, the recreation of the data-engine and regeneration of the previously generated files should show the same outcome, i.e. the two images above should show the same structure. 

### Steps To Reproduce

I compiled a bash script of curl commands to reproduce the steps described above. You need to adjust the EgeriaURL (I needed to adjust the file ending to be able to upload it)
[test-script.txt](https://github.com/odpi/egeria/files/7433910/test-script.txt)
 

### Environment

```markdown
- Egeria: Tutorial Compose, V3.2
- OS: Ubuntu Server 18.4
- Java: 11
- Additional connectors and integration: Only the ones available in the Egeria tutorial
```

### Any Further Information?

See also [Slack channel](https://lfaifoundation.slack.com/archives/C01F40J2XA8/p1635414256052700)

**Comment by marius-patrascu** [comment] 2021-11-08 11:16
I tried reproducing the issue but on my side it works fine. Also the delete operation for a data engine is not supported yet. I got in touch with the issue reporter and explained all of this. 

I will close the issue since I cannot reproduce it after following the provided steps.

**Closed by marius-patrascu** 2021-11-08 11:16 UTC
Labels: bug, triage
