### ISSUE TITLE
CTS failure

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3121] opened 2020-05-29 16:22 UTC
Logs in 'cts-inmem-master.out' , master @ 689f7d418d417f883df48a964f4b78313b170a27

1 CTS failure
```
        "testFailedCount": 1,
```
...
```
                "class": "OpenMetadataConformanceWorkbenchResults",
                "failedTestCases": [
                    {
                        "class": "OpenMetadataTestCaseResult",
```
...
```
                        "unsuccessfulAssertions": [
                            "repository-relationship-property-search-13: findRelationshipsByPropertyValue with general regex found (guid=5a5ae9e3-6863-4c12-b624-9400af81f4cc) un
expected results using parameters: {asOfTime=null, fromRelationshipElement=0, limitResultsByStatus=null, pageSize=10, relationshipTypeGUID=e5d7025d-8b4f-43c7-bcae-1047d650b94a,
searchCriteria=.*ery..*, sequencingOrder=null, sequencingProperty=null}"
                        ]
```

Originally found when testing #3056 . Reproduced in master (above)

**Comment by planetf1** [comment] 2020-05-29 16:28
This error did not occur in a graph repo test on the #3056 PR, but did also occur on the inmem repo there.

**Comment by grahamwallis** [comment] 2020-06-01 07:43
@planetf1 Do you have the logs for this? The link above seems to point to a PR that cleans up imports in Subject Area. I'm happy to take a look at the failure but it'd be great to see the failure log. 

Is the implication of the above that we think this was introduced by the secure protocols change?

**Comment by planetf1** [comment] 2020-06-01 08:24
Apologies, I thought I had added the link.

it is at https://ibm.box.com/s/jq8zjqueagguh1ernrezyd35rc9teksy - look for the file 'cts-inmem-master.out'

**Comment by grahamwallis** [comment] 2020-06-01 14:41
I think I have found (and fixed) the problem. Just doing a complete build and CTS run against in-memory repository, then will push a PR.

**Comment by grahamwallis** [comment] 2020-06-01 16:31
I think the problem was being caused by inadequate matching during construction of the expected instance sets in the advanced search tests. This was missing the fact that for a findXXXByPropertyValue an attribute value such as 'queryId', or any extension of it as used in the advanced search tests, would match a truncated and contained search pattern based on an attribute value such as 'query.13' (i.e. the value assigned to the 'query' attribute for the 13th seed instance of the relationship type SchemaQueryImplementation). 

It was during commit 72d3027 (14 days ago) that the queryId attribute was added to the relationship type - so that would explain why we have not seen this problem before.

I have modified the construction of the expected instance sets so the CTS is should not be surprised by a returned matching instance.

I have built and run a full CTS test against the in-memory repository and it is clean.
I don't understand why the same problem did not appear to afflict the graph repository. I would have expected all repositories to have seen the same issue. I am running a full CTS test against the graph repository now and will investigate further if it shows any anomalies.

**Comment by grahamwallis** [comment] 2020-06-02 08:09
The CTS run with graph repo was also clean (apart from a timing issue with one ref copy, which I have subsequently looked for by GUID using postman and it does exist, so I am concluding that this was just a timing issue). I therefore think the fix is good to go and will proceed to merge.

**Closed** 2020-06-02 08:42 UTC
Labels: conformance-testing
