### ISSUE TITLE
findEntitiesByProperty does not work with local graph repository

### ISSUE THREAD

**Issue by popa-raluca** [odpi/egeria#1194] opened 2019-06-28 10:11 UTC
findEntitiesByProperty does not work with local graph repository. The entity can be found with Gremlin in the graph. 
I run into this issue while testing DataEngine with the local graph. It worked with Atlas repository & in memory repository.

2019-06-28 12:37:29.899 DEBUG 3694 --- [io-5500-exec-10] .o.o.a.r.g.r.GraphOMRSMetadataCollection : findEntitiesByProperty: continuing with search for entity type SchemaAttribute because it is a subtype of SchemaAttribute
2019-06-28 12:37:29.900 DEBUG 3694 --- [io-5500-exec-10] o.o.o.a.r.g.r.GraphOMRSMetadataStore     : findEntitiesByProperty primitive match property has key qualifiedName value (host_(engine))=INFOSVR::(data_file_folder)=/::(data_file_folder)=data::(data_file_folder)=files::(data_file_folder)=CocoPharma::(data_file)=Employee-Employee.csv::(data_file_record)=Employee-Employee::(data_file_field)=ROLE(host_(engine))=INFOSVR::(transformation_project)=dstage1::(dsjob)=file_to_EMPLOYEE::(stage)=CompDir_EmployeeCSVDemo1
2019-06-28 12:37:29.901 DEBUG 3694 --- [io-5500-exec-10] o.o.o.a.r.g.r.GraphOMRSMetadataStore     : findEntitiesByProperty primitive match property has property criterion [HasStep([ReferenceablexqualifiedName.textRegex(.*(host_(engine))=INFOSVR::(data_file_folder)=/::(data_file_folder)=data::(data_file_folder)=files::(data_file_folder)=CocoPharma::(data_file)=Employee-Employee.csv::(data_file_record)=Employee-Employee::(data_file_field)=ROLE(host_(engine))=INFOSVR::(transformation_project)=dstage1::(dsjob)=file_to_EMPLOYEE::(stage)=CompDir_EmployeeCSVDemo1.*)])]
2019-06-28 12:37:29.902 DEBUG 3694 --- [io-5500-exec-10] o.o.o.a.r.g.r.GraphOMRSMetadataStore     : findEntitiesByProperty traversal looks like this --> [GraphStep(vertex,[]), HasStep([~label.eq(Entity), vetypeName.eq(SchemaAttribute), veentityIsProxy.eq(false)]), OrStep([[HasStep([ReferenceablexqualifiedName.textRegex(.*(host_(engine))=INFOSVR::(data_file_folder)=/::(data_file_folder)=data::(data_file_folder)=files::(data_file_folder)=CocoPharma::(data_file)=Employee-Employee.csv::(data_file_record)=Employee-Employee::(data_file_field)=ROLE(host_(engine))=INFOSVR::(transformation_project)=dstage1::(dsjob)=file_to_EMPLOYEE::(stage)=CompDir_EmployeeCSVDemo1.*)])]])] 
2019-06-28 12:37:29.905 DEBUG 3694 --- [io-5500-exec-10] o.j.g.transaction.StandardJanusGraphTx   : Guava vertex cache size: requested=20000 effective=20000 (min=100)
2019-06-28 12:37:29.906 DEBUG 3694 --- [io-5500-exec-10] o.j.g.t.vertexcache.GuavaVertexCache     : Created dirty vertex map with initial size 32
2019-06-28 12:37:29.906 DEBUG 3694 --- [io-5500-exec-10] o.j.g.t.vertexcache.GuavaVertexCache     : Created vertex cache with max size 20000
2019-06-28 12:37:29.907 DEBUG 3694 --- [io-5500-exec-10] o.j.g.t.JanusGraphBlueprintsGraph        : Created new thread-bound transaction standardjanusgraphtx[0x67dd1a79]
2019-06-28 12:37:30.246 DEBUG 3694 --- [nsumer.outTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [ineage.outTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [Engine.outTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [hort1.OMRSTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [atform.outTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [latform.inTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [fficer.outTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.246 DEBUG 3694 --- [onView.outTopic] o.a.e.t.k.KafkaOpenMetadataEventConsumer : Found records: 0
2019-06-28 12:37:30.323  INFO 3694 --- [io-5500-exec-10] .o.o.a.r.g.r.GraphOMRSMetadataCollection : findEntitiesByProperty: for type SchemaAttribute found no entities

[findEntitiesByProperty_schemaAttribute.log](https://github.com/odpi/egeria/files/3338689/findEntitiesByProperty_schemaAttribute.log)

**Comment by grahamwallis** [comment] 2019-07-08 10:57
Hi @popa-raluca - Can you please describe the process by which the entity was added to the repository? I am wondering if it is a proxy or a full (local) entity.

**Comment by popa-raluca** [comment] 2019-07-08 12:22
Hi @grahamwallis - I run into the issue while trying to run Data Engine with the local graph. The entities are not proxies, they are created using the createEntity method(which uses  metadataCollection.addEntity) from RepositoryHandler.
In the tests done last week, I saw that a SoftwareServerCapability entity can be retrievied with findEntitiesByProperty, but SchemaType(TabularSchemaType) and SchemaAttribute entities are not retrived. Im only searching based on the qualifiedName, not sure if this is helpfull.
If you want, we can have a call to discuss more details.

**Comment by grahamwallis** [comment] 2019-07-08 16:37
@popa-raluca - thanks Raluca - I will try to reproduce it.

**Comment by popa-raluca** [comment] 2019-07-09 11:14
@grahamwallis - Hi Graham, I tested with some simple qualifiedNames and it works.

**Comment by popa-raluca** [comment] 2019-07-10 12:58
@grahamwallis Hi Graham, I did some more tests and I now have another issue, that might be related to this one - if I have 2 entities in the graph with the qualifiedNames TAX and TAXP, then searching for the qualifiedName TAX will return both entities

**Comment by grahamwallis** [comment] 2019-07-12 16:41
@popa-raluca  - Hi Raluca, There are two (separate) problems here. One is that the findEntitiesByProperty() method extends the search string to make it match a substring of the actual property value; the second problem is special characters in the regex syntax.
Regarding the first problem I have made a code change to the graph repo that will only do substring matches for findXXXByPropertyValue() - because this is a broad search-style interface. For the findXXXByProperty() or findEntitiesByProperty() interfaces - which are by their nature more specific, precise retrievals, I have removed the extension of the regex string; so that the regex string will be looking for a fully matching property value (or classification name). This will prevent you getting back more than you wanted - in the example of TAX and TAXP. 
The other problem is about the regex syntax - and particularly the role of special characters in the syntax, such as dots, plus signs, stars, parentheses, brackets, etc. Having discussed this with Mandy we want to continue to expose the full regex syntax because it will provide the flexibility to perform appropriate matches; the disadvantage is that the search string (at least at the OMRS interface) needs to be regex-aware. My proposal for addressing this is to add documentation about the search interface, and to make sure that both the in-memory and graph repositories are consistent in their support. In the meantime, to perform a match of a property value that contains any of the special characters, escape the special characters so that they are included as part of the pattern. For example, to find an entity with qualifiedName="outer(inner)" (and avoid any other matches) the regex string would be "outer\(inner\)". Note that if you issue this string in a REST command from Postman for example you need to double-escape the parentheses, i.e. "outer\\(inner\\)".
I hope this helps. I will document this properly, and will also spend some time testing and thinking about the findXXXByPropertyValue methods - especially as they take the search string as a URI parameter and the additional HTML escaping gets awkward. 

I will push my "Issue1194" PR soon and will add the documentation and further update here.

**Comment by grahamwallis** [comment] 2019-10-30 10:52
Fixed by #1522

**Closed by grahamwallis** 2019-10-30 10:52 UTC
Labels: bug
