### ISSUE TITLE
catch (Throwable  e) and catch(Exception e) without logging 

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2172] opened 2019-12-06 08:50 UTC
`catch(Throwable  e)` and `catch(Exception e)` need to log in the logger.

Example:

                            catch (Throwable  error)
                            {
                                OMAGAdminErrorCode errorCode = OMAGAdminErrorCode.BAD_ACCESS_SERVICE_ADMIN_CLASS;
                                String        errorMessage = errorCode.getErrorMessageId()
                                                           + errorCode.getFormattedErrorMessage(serverName,
                                                            accessServiceAdminClassName, 
                                                            accessServiceConfig.getAccessServiceName());

                                throw new OMAGConfigurationErrorException(errorCode.getHTTPErrorCode(),
                                                                          this.getClass().getName(),
                                                                          methodName,
                                                                          errorMessage,
                                                                          errorCode.getSystemAction(),
                                                                          errorCode.getUserAction());
                            }

This leads only to AuditLogs like:

` OMAS-DATA-ENGINE-0004 The Data Engine Open Metadata Access Service (OMAS) is unable to initialize a new instance; error message is Failed to construct kafka consumer`

And response like:

`OMAG-ADMIN-400-011 The OMAG server omas has been passed an invalid admin services class name org.odpi.openmetadata.accessservices.assetlineage.admin.AssetLineageAdmin for access service Asset Lineage`

which are not very useful to identify what technical issue is even if you set the logger on debug, because the original exceptions are lost. In the example could be kafka down or missing topic or wrong ssl connection etc.

For the cases of `catch (Throwable  e)` and` catch(Exception e)` e needs to be logged with logger and or included in the new throw.

**Comment by bogdan-sava** [comment] 2019-12-06 08:52
Logging e will not affect the AuditLog. For the users only want AuditLog logger is turned off.

**Comment by bogdan-sava** [comment] 2019-12-06 09:03
It happens for all the Admin classes, in the initialize method.

        catch (OMAGConfigurationErrorException error)
        {
            throw error;
        }
        catch (Throwable error)
        {
            auditCode = AssetOwnerAuditCode.SERVICE_INSTANCE_FAILURE;
            auditLog.logRecord(actionDescription,
                               auditCode.getLogMessageId(),
                               auditCode.getSeverity(),
                               auditCode.getFormattedLogMessage(error.getMessage()),
                               null,
                               auditCode.getSystemAction(),
                               auditCode.getUserAction());
        }

Including error.getMessage() in auditLog is not good enough for technical debugging as the root cause is lost and there are error without message.

**Comment by mandy-chessell** [comment] 2019-12-06 09:07
The logging is no use to track down a technical issue if the person doing the debugging is not able to see the code.  These error messages are more explict than logging messages because they include what happened and how to fix it.

So the reporting of this issue is correct because it should be possible to debug the error from the audit log records (not just the message) and exceptions thrown.  However the solution to add logging messages to supplement the deficiencies of the audit log messages and the exception content is not correct.

The audit logging and exception should be improved to describe the issue so it can be debugged.  Audit log messages that record an exception can include the exception in the audit log record - even if the exception is not included in the error message.

I agree in the example above, the original exception should also be included in the new exception - and the stack trace logged in the audit log on exit from the server.

**Comment by bogdan-sava** [comment] 2019-12-06 09:34
Hi Mandy,

Thanks for the fast answer. Logging and AuditLog are not exclude each other.
I agree that AuditLog should be also improved, and I agree that logging is useful only for people like us that are able to see the code. This is exactly what I mean. 
In this phase we are trying to deploy the app in prod and we are able to see the code also. I can't see any reason not to have both.
Simply adding one logging line and improve also the AuditLog to be more useful, are making app more powerful and give options in usage.
This will allow us to move faster. Later on, when env will be more stable, and handed over, debugging can be turned off.

    catch (OMAGConfigurationErrorException error)
    {
        throw error;
    }
    catch (Throwable error)
    {
        log.error(error);
        auditCode = AssetOwnerAuditCode.SERVICE_INSTANCE_FAILURE;
        auditLog.logRecord(actionDescription,
                           auditCode.getLogMessageId(),
                           auditCode.getSeverity(),
                           auditCode.getFormattedLogMessage(error.getMessage()),
                           null,
                           auditCode.getSystemAction(),
                           auditCode.getUserAction());
    }

**Comment by mandy-chessell** [comment] 2019-12-06 10:03
I am sorry this is not the right response - if you can not diagnose the problem with the audit log and exception messages then there is a problem with these diagnostics and they need to be fixed.  Circumventing the problem by putting in logging messages is a hack that will not get the underlying error in the diagnostics fixed.  Once the problem is diagnosed via the hack, no-one goes back and fixes the diagnostics.

The logging is fine for developers when they are initially writing their code.  However, when deploying or running in production it is very important that the logging is not relied on because in addition to the lack of proper explanation in the log messages, the loggger does not understand the server divides and lumps messages from different servers together.  The audit log is server-aware which means the diagnostics can be managed on a server by server basis.

**Comment by mandy-chessell** [comment] 2019-12-06 10:08
There seems to be two levels of problem here.  If I look at the example above, the final catch of Throwable should only be reached for a non-checked exception.  Errors such as Kafka config errors should be handled by the called class and returned as `OMAGConfigurationErrorException`.

If we are not seeing that behaviour then it needs to be addressed.

For the audit log message above, the code should be changed to call logException() on the audit log and pass the exception.  The call to `log.error(error);` should be removed.

**Comment by mandy-chessell** [comment] 2019-12-06 10:12
Getting the diagnostics right is difficult and it takes explicit testing and focus.  The process of deploying to production is a good opportunity to validate the diagnostics.   Each new deployment environment will uncover new flaws in the diagnostics - but over time these lessen and others coming to deploy get meaningful diagnostics as a result.

**Comment by bogdan-sava** [comment] 2019-12-06 10:40
Having error logged in the logging is not a hack. Is a choice to see it. 
Adding proper AuditLog choice also is another option.
I want to have them both.

**Comment by bogdan-sava** [comment] 2019-12-06 10:56
I agree that during the time we can improve the audit log, but till then we are stuck with no diagnostics whatsoever. Having the option to activate logging see what happens would have been more than useful.

**Comment by bogdan-sava** [comment] 2019-12-06 11:01
On the other hand logging has a mechanism to set the level you want to see and even turn it off.
Putting the stack trace in AuditLog might lead to having sensitive information on AuditLog. Not a good idea.

**Comment by bogdan-sava** [comment] 2019-12-06 11:02
Logging the error in the logging seems to be a better and versatile option for emergency cases.

**Comment by mandy-chessell** [comment] 2019-12-06 11:05
Actiually it is the other way around - the audit log is designed to hold sensitive information - the logging is not.  This is partly because the logging is not server aware and sends all messages to the destination defined for the platform.

The discussion seemed to be about whether the calls to the audit logging are corrected to produce the diagnositcs or whether additional calls are made to the logging service to bypass the errors in the calls to audit logging.   There is no disagreement on whether the diagnostics need to be fixed.

**Comment by GuyAckermans** [comment] 2019-12-06 11:08
I see the point that relying on the logging during development may lead to neglect of proper audit logging. However, if the AuditLog is not perfect yet for all components and the system has to go in production anyway, there would not be any mechanism for the production team at all to properly diagnose errors. I agree with Bogdan that the capacity for the production team to properly diagnose should take priority over this incentive mechanism for developers to properly write auditlogging. The concern that developers will become "lazy" with their auditlogging could better be solved with explicit peer reviewing of their auditlogs instead.

**Comment by mandy-chessell** [comment] 2019-12-06 11:12
Our goals are the same - making sure that the diagnostics are available to the deployers.   This is not about avoiding fixing the problem - this is about advocating a hack rather than fixing the problem properly.

**Comment by bogdan-sava** [comment] 2019-12-06 11:15
Logging exception is not a hack. Never was. It will never be.

**Comment by mandy-chessell** [comment] 2019-12-06 11:16
It is in this case -because it is being proposed instead of fixing the calls to the audit logging.

**Comment by bogdan-sava** [comment] 2019-12-06 11:39
Not instead! Additional to fixing the audit.

**Comment by bogdan-sava** [comment] 2019-12-06 11:39
Logging is never fixing. It helps.

**Comment by mandy-chessell** [comment] 2019-12-06 12:18
In this case it is not helping because it gives no more information that the audit logging and exception handling should give.  Adding logging at this stage will create 2 situations:

* the diagnostics are never fixed and other organizations suffer 
* the diagnostics are fixed and we have superflous calls to the logging scattered throughout the code.

The only value I can see in adding the logging code is to help debug the diagnostics - however I would rather add the logging calls to the audit log code than have it throughout the server-specific code.

For the platform services, that operate outside of the server context then logging makes sense.

**Comment by bogdan-sava** [comment] 2019-12-06 13:10
I disagree.
Logging is harmless and can be switch on and off. 
Logging is also offering the versatility to setup the verbosity through the severity level, package and class level.

Let's fix the audit log but also adding logging.

**Comment by mandy-chessell** [comment] 2019-12-07 08:10
Logging is not harmless - it takes time, can leak information and can swamp the person tracking down the problem.  And in this case we are talking about operational errors.  So we are looking for output that enables this person to get to the cause of the error very quickly.

The control of output from the audit log is also possible.  This is not unique to logging.

The picture below shows 3 servers configured for high availability.   As such they are each running on 4 platforms.

<img width="393" alt="Screenshot 2019-12-07 at 07 56 07" src="https://user-images.githubusercontent.com/12354195/70371118-14846180-18c7-11ea-8192-bd059b717db1.png">

All of the resources such as the Kafka event bus and topics are configured on a per server basis.

The result of the call to `log.error(error)` causes a record to be output with details such as the date/time, pid of the platform and the class name of the caller and details of the exception.  There is no information about which server the error came from - and hence it is hard to work out which server is reporting the problem, and which resources are in peril.

Now consider that the platforms are being operated by a cloud provider and the servers are run by their customers.  The output of the logging goes to the cloud provider and the output of the audit log goes to the people running the servers.  Since the server owners are the ones controlling the configuration, and they own the resources being used by the server, they are the people that need the diagnostic information.   They may also not want information about what their server is doing, how it is configured etc going to the cloud provider.

Ideally I would like all logging to be removed from the server code.  However I know developers like it and it is useful for development.  This issue is not discussing the needs of the developer.  It is about creating diagnostics for operations which is why using logging is not the right solution.

**Comment by mandy-chessell** [comment] 2019-12-07 08:23
Since you are writing your own audit log destination connector to use in your deployment environment, you could output the exceptions to the logger in your connector.  I have been thinking as a result of this conversation that I will change the console audit log destination connector that we typically use in development to output the exception and stack trace to the console if/when they occur.  It already calls log.error().   This means we can validate that the right information is being captured through the audit log whilst giving developers easy access to the diagnostic information.

**Comment by bogdan-sava** [comment] 2019-12-09 09:58
I totally disagree.
Logging can be turned off for the ones who don't use it or like it.
It takes time, as all other lines of code, including audit log.
In our case, it was definitely the fastest way to get the cause of the error. All developers on our side relay on it on development and, most important, on deployment.

The logging format and information are up to the developer and settings. If developer want to add information about the server, nothing can stop that. Also information about timestamp and thread, class method are in the logger config. Moreover is very easy to setup the split.

I am no questioning the usage of audit log. I am questioning missing logging. We all are using here and it is very useful. Even in production env, where let's say is turned off by default, it is still the last resort for debugging and diagnostic.

**Comment by danielaotelea** [comment] 2019-12-09 12:12
If there is no connection present (for example, there is no connection to the GT), the response does not include the connection list.

**Comment by mandy-chessell** [comment] 2019-12-15 21:41
We are agreeing that the logging is great for developers and they are free to log what they want. 
The values that you say are in the log header - but not the server name - which is critical in our multi-tenant world.  As you say - the logging is meaningful to the developer and we do not prevent component owners from using this logging mechanism for their own purposes.

The audit log mechanism collects the context information about the server and the component automatically - and does not rely on the developer to add this information to every log message.
It also focused on providing diagnostic information to people other than the code developers.  This includes deployers.

I have updated the logging of the instance failure exception to call logException rather than logRecord in each of the access services.  This means the exception is passed to the audit log.

I have has a look at the audit log implementation and we can certainly make some improvements around logging of exceptions and stack traces when logException is called.  At the moment the details of the exception are added to the additional information array.  I can extend the log record to explicitly log the exception class name, message and stack trace.  This means we are capturing this information for each logged exception and it is easier for an automated log managger to process.

I can then extend the console log destination to log the exceptions on the console for dev environments.

I will look into creating an audit log destination for log4J which means the server owner can choose if their server pushes the audit log records to log4J or not.  I was thinking of a component hierarchy of <serverName>.<componentName>.  This means the logging output can be controlled on a server or server/component basis.  

I will also add an implementation to the file audit log destination.  At the moment this is a placeholder.  This destination will support the querying of log records which will be particularly useful in our hands on labs.

We also have has a request for an event bus destination.  I will put that one in while I am working on the logging - but may be not in the first commit.

Finally it looks like it would help to add additional admin calls to make it easier to set up the audit log destinations.  At the moment you need to do it through the repository services config endpoint which is tricky.

**Comment by planetf1** [comment] 2019-12-16 08:17
Interesting suggestion - I like the idea of applying some of the flexibility classic logging offers (but with a code structure/developer centric approach) with a more 'application'-centric approach.

A couple of thoughts specific to the log4J suggestion - Given slf4j seems to have mostly superceeded log4J, perhaps that is the appropriate connector. We'll have to clarify how to override the configuration too as usually slf4j (and other logging infra) has a particular search order for locating their config files

This of course is quite specific to the destination

**Comment by bogdan-sava** [comment] 2019-12-16 09:09
Java logging API is open for extension. It is compliant with SOLID principles. I am refering tyo the open close principle. The header can be extended very easy if we want to add fields there. Of course can be done automatically. 
Destination and verbosity and filters of logs can be also very easy to setup.

Also there is a very easy way to take logs from file and publish to kafka topic, and according to experience is more reliable than publish directly.

But, I was not talking about audit log. I was talking about the need of using java logging API properly. I was talking swallowing exceptions in many points without logging. And the logging needs to be produced by that class in order to be useful. This has nothing to do with audit log. Nevertheless we almost have no .debug logging, which is also very useful in real life, especially on the very first usages of the app.

**Comment by cong78** [comment] 2020-03-04 10:49
![IMG_3725](https://user-images.githubusercontent.com/11947525/75872272-24e8a180-5e0e-11ea-9497-22fef25c8e17.jpg)

Some inputs for this topic from previous discussion.

**Comment by mandy-chessell** [comment] 2020-06-05 12:53
I am going to close this because the discussion has stopped.

**Closed by mandy-chessell** 2020-06-05 12:53 UTC
Labels: consumability, no-issue-activity
