### ISSUE TITLE
[user-issue] 400 Bad Request: Connecting Endpoint to Connector

### ISSUE THREAD

**Issue by PatricioMacedo** [odpi/egeria#6719] opened 2022-07-14 14:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting 400 BAD REQUEST when using API call to link connection and endpoint. What im trying to do is link both of these and then be able to link this to my data store instance in Asset Manager. 

### Expected Behavior

Link a connection to an endpoint: 200 Success

### Steps To Reproduce

[/servers/{serverName}/open-metadata/access-services/data-manager/users/{userId}/connections/{connectionGUID}/endpoints/{endpointGUID}]

Using this endpoint, i am using this payload:

ServerName: myServer
userid: garygeeke
connectionguid: ---
endpointGUID:---
Request Body:
{
  "externalSourceGUID": "d597724c-fb3a-4286-a31c-13aa47101d13",
  "externalSourceName": "DBM01"
}

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment] 2022-07-15 10:20
See https://github.com/odpi/egeria/issues/6717 for some analysis of your original issue with Data Manager & getting a 400 error. There are some tips there to enable debug -- the issue is that the egeria code doesn't even get called as tomcat/jackson can't map the request. (Also in that issue are notes to update docs, make it easier to debug etc)

**Comment by planetf1** [comment] 2022-07-15 10:29
For this particular request, the body needs to be something like: (with default values)
```
{"class":"MetadataSourceRequestBody","externalSourceGUID":null,"externalSourceName":null}
```
so you are missing the 'class'

This is down to how we generate the REST API from the Java Objects using jackson. 

We generally recommend using the Java API, as this correctly fills in the body, and has additional client side checks. Unfortunately the swagger rest API doc is problematic and does not cover this aspect.

Hope that helps.

(I determined this answer from looking at the source code, determining the body was MetadataSourceRequestBody, then using some code like this to print the serialized body: https://github.com/planetf1/egeria-body-viewer - but this shouldn't be needed )

**Comment by planetf1** [comment] 2022-08-07 12:58
Closing as I think the above answers the question - please do get back to us if you need further help/clarifications

**Closed by planetf1** 2022-08-07 12:58 UTC
Labels: bug, triage
