### ISSUE TITLE
Adding Assets to the  Catalogue Fails in the Tutorial Labs

### ISSUE THREAD

**Issue by sarathsasidharan** [odpi/egeria#2959] opened 2020-04-22 09:21 UTC
Issue 

Adding assets to the catalogue in https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-labs/asset-management-labs/building-a-data-catalog.ipynb does not work. 

Error 

OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during addCSVFileToCatalog request for open metadata access service Asset Owner OMAS on server cocoMDS1; message was OMRS-REPOSITORY-400-030 A property called delimiterCharacter of type Primitive has been proposed for a new metadata instance of category EntityDef and type CSVFile; this property should be of type string in open metadata repository cocoMDS1
 * The system is unable to process the request because of an internal error.
 * Verify the sanity of the server.  This is probably a logic error.  If you can not work out what happened, ask the ODPi Egeria community for help.

Step to Replicate 

Follow the lab building-a-data-catalogue and execute cell 7 , this will give this error

![image](https://user-images.githubusercontent.com/9977936/79964739-6818d580-848b-11ea-8510-e31bda1e5f58.png)

**Comment by planetf1** [comment] 2020-04-22 10:37
Thanks for reporting. Have just checked and hit the same issue. This is a regression

**Comment by sarathsasidharan** [comment] 2020-04-22 10:43
thanks , also see this issue in https://github.com/odpi/egeria/blob/bb959d2adbde3aaaa5edcfdb4313c6418d45b656/open-metadata-resources/open-metadata-labs/ui-labs/ui-asset-search.ipynb

This is cell 5.

![image](https://user-images.githubusercontent.com/9977936/79972799-c9927180-8496-11ea-8d5b-055708b81c92.png)

**Comment by mandy-chessell** [comment] 2020-04-22 10:52
Thanks for rasing this - I have a look at it

**Comment by grahamwallis** [comment] 2020-04-22 10:54
@sarathsasidharan @mandy-chessell Thanks for raising the issue Sarath. This looks to me like it is caused by the EntityDef for CSVFile expecting a String when the delimiterCharacter is a Character.

I recently tightened up the type checking in the repository validator and I think it may be the the now tighter checking has identified the mismatch.

**Comment by planetf1** [comment] 2020-04-22 11:06
Probably introduced in #2937 - thanks for looking Mandy. We'll need to get this fix into the 1.7 branch too (and for running labs). I can do the cherry pick if you like once we have a fix in master.

**Comment by mandy-chessell** [comment] 2020-04-23 10:43
I have fixed 2 things:

* The error message when the type is wrong - looks like this:

```
No assets created
OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during addCSVFileToCatalog request for open metadata access service Asset Owner OMAS on server cocoMDS1; message was OMRS-REPOSITORY-400-030 A property called delimiterCharacter of type char has been proposed for a new metadata instance of category EntityDef and type CSVFile; this property should be of type string in open metadata repository cocoMDS1
 * The system is unable to process the request because of an internal error.
 * Verify the sanity of the server.  This is probably a logic error.  If you can not work out what happened, ask the ODPi Egeria community for help.
Result of creating an asset is: 
[]
```
* Also change Asset Owner OMAS to pass strings rather than characters so the notebook works again.

**Comment by planetf1** [comment] 2020-05-04 09:00
This is fixed now. closing

**Closed by planetf1** 2020-05-04 09:00 UTC
Labels: bug, notebooks, regression, release, user-issue
