### ISSUE TITLE
Ui tenancy Add governance server specific backend configuration

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1575] opened 2019-09-17 11:28 UTC
Add omas specific backend configuration. This is required as a given endpoint may support a subset of omases.

**Comment by mandy-chessell** [comment] 2019-09-18 16:12
This issue seems to be a duplicate of #1583.  Same comment applies.  We should not allow a UI Tenent to be configured with multiple metadata servers.  It will need the information for the governance servers that the users need to connect with.  However, ideally, these governance servers would be connected to the same metadata server as the UI Tenant.

**Comment by davidradl** [comment] 2019-09-20 09:47
I have changed the title of this issue so it only applies to governance servers. @mandy-chessell can I check I am understanding this correctly we are looking to allow ui configuration for endpoints of the governance servers it needs to talk to (the existing application.properties contains separate configuration entries for the lineage server and the omas server)?

**Closed** 2020-05-20 00:03 UTC
Labels: enhancement, no-issue-activity
