### ISSUE TITLE
Build output for pr build is so long I cannot see the errors at the end 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5463] opened 2021-07-05 14:30 UTC
I am not sure if this an issue for just pr builds - I keep trying to scroll down to the bottom to see the errors - in the maven output but the page is still loading content - I cant get down to see the error.

This seems like a regression to me, as it was not like this on previous builds I tried. 

It is failing on:
https://github.com/odpi/egeria/pull/5410/checks?check_run_id=2989205958

I notice that info level logging is in the console output, I wonder if we could run with warning level to reduce the output.

**Comment by davidradl** [comment] 2021-07-05 14:37
I notice that the gradle output is 8812 lines long but the maven output truncates at 67000 lines 

[INFO] Mon Jul 05 10:49:25 UTC 2021 serverinmem Types OMRS-AUDIT-0301 The local server has added a new type called GovernanceActionTypeUse with a unique identifier of 31e734ec-5baf-4e96-9f0d-e8a85081cb14 and a version number of 1 from Egeria (2.11)
[INFO] Mon Jul 05 10:49:25 UTC 2021 serverinmem Types OMRS-AUDIT-0301 The local server has added a new type called TargetForAction with a unique identifier of 46ec49bf-af66-457
This step has been truncated due to its large size. Download the full logs from the  menu once the workflow run has completed.

**Comment by planetf1** [comment] 2021-07-05 15:48
A few aspects I see to this
 a) You can download the full maven logs  by clicking on the '...' and downloading the full archive
<img width="1354" alt="Screenshot 2021-07-05 at 16 43 51" src="https://user-images.githubusercontent.com/7292002/124495628-3fd77700-ddb0-11eb-9303-48d110aa0472.png">

 b) The logs are long. An alternative would be to ensure that i) the stdout/stderr is kept brief ii) all output is saved in files iii) files are added as attachments/archive to the build task (but in your use case you'd still need to be downloading another file) . In particular the area you are interested in is particular verbose and I would consider removing it's output so viewers get a better top level view
 
 c) There is an inconsistency with the gradle build as you point to, which is more terse.
 
 My gut feel is to go along the lines of b) in the long term .. and since the medium term target is a gradle switch, perhaps that's a good place to start, just ensuring additional output is saved. 
 
 For now does a) get you working?

**Comment by planetf1** [comment] 2021-07-05 15:54
A comment on 'regression' -- the management of that logging output is entirely down to github - so could be size related, or browser, etc but not something that we can control (other than points above)

**Comment by davidradl** [comment] 2021-07-05 16:14
hi Nigel, I can see the error in the Gradle output, so I am working. On the regression front, it could be just my perception, but I have not experienced  this as stopping me from seeing the error before- while  looking at Maven output.

**Comment by planetf1** [comment] 2021-07-07 15:52
I think it worth keeping this open, but suggest we target the gradle build for improvements here.
The point about not being able to see the error simply is an important one - the challenge is how to easily make that available.
If output from all the busy tasks is logged instead, there's still a jump to go retrieve it, which would also apply in the local case - but it's probably what we need to do. I think the top level output should be enough to quickly and simply identify the failing task, whilst for debugging/understanding precise failure, looking at further logs is sufficient.
This should then be covered in the docs when we talk about builds, and in the dev guidelines.

**Comment by planetf1** [comment] 2023-03-23 23:31
Is the gradle log better?
Can we close this - or are there specific things you want to add?

**Closed** 2023-05-23 12:11 UTC
Labels: build-improvement, pinned, gradle
