### ISSUE TITLE
Background job still runs after data-engine proxy server instance is deleted

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4093] opened 2020-10-13 15:41 UTC
While testing data-engine proxy server noticed that background thread (poller job) is not canceled and resource is not released.
The server instance was deleted via admin-services API

Example:
DELETE https://localhost:8081/open-metadata/admin-services/users/admin/servers/datastage-proxy/instance

After closing the connector we should also cleanup/stop all background jobs/threads it created.

**Comment by cmgrote** [comment] 2020-11-12 13:21
The issue is that there is no call to the `disconnect()` method of `DataEngineProxyOperationalServices` from within the `deactivateRunningServiceInstances` method of `OMAGServerOperationalServices` -- hence transferred the issue to this repo, as all of this code is here in the core repo (not specific to any data engine proxy connector).

**Closed** 2020-11-16 14:08 UTC
