### ISSUE TITLE
Event mapper not working

### ISSUE THREAD

**Issue by SoyGabor** [odpi/egeria#1318] opened 2019-07-24 11:05 UTC
Hi,

I'm trying to configure a logical server on the OMAG platform to work with an instance of Apache Atlas. I'm following the tutorial on https://www.odpi.org/blog#startup but I am having problems with the event mapper configuration. Any help would be much appreciated. I'm using the Atlas image provided by Egeria. This is the response that I get when I try to instantiate the logical server:

{
    "class": "SuccessMessageResponse",
    "relatedHTTPCode": 500,
    "exceptionClassName": "org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException",
    "exceptionErrorMessage": "OMAG-ADMIN-500-001 Method activateWithSuppliedConfig for OMAG server EgeriaMetadataServer1 returned an unexpected exception of org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSConfigErrorException with message OMRS-LOCAL-REPOSITORY-400-001 The repository event mapper configured for the local repository for server EgeriaMetadataServer1 is not accessible.",
    "exceptionSystemAction": "The system is unable to configure the OMAG server.",
    "exceptionUserAction": "This is likely to be either an operational or logic error. Look for other errors.  Validate the request.  If you are stuck, raise an issue.
}

**Comment by mandy-chessell** [comment] 2019-07-24 11:11
It looks like the event mapper class is not in the server platform's class path? @cmgrote ?

**Comment by cmgrote** [comment] 2019-07-24 12:24
Hi @SoyGabor -- thanks for raising the issue.  This could be for a number of reasons:

- As Mandy points out, it could be that you're missing the necessary `.jar` file or environment variable for it to be loaded.  You need to have `LOADER_PATH` defined (or sent to the `java` command as `-Dloader.path=...` and pointing to the location of the Apache Atlas connector jar file (https://github.com/odpi/egeria-connector-apache-atlas/releases/download/1.1-SNAPSHOT/egeria-connector-apache-atlas-package-1.1-SNAPSHOT.jar) in your Egeria image.  (If you're using our `vdc` Helm chart to run your environment, this should be done for you automatically already...)
- There could also be a resolution issue between your Apache Atlas environment and your Egeria environment (ie. assuming they're running on different hosts or different pods within k8s).  This is a nuance of Kafka: that when it response to a connection it responds back with listener addresses, which may or may not be network-known to the other host.  (If they're not known to the other host, then further attempts to connect to Kafka brokers will fail.)

If you can enable additional logging in your Egeria environment prior to startup by setting the environment variable `LOGGING_LEVEL_ROOT=INFO` (or even `DEBUG`) before running the server chassis, and share the console output it produces, this should help narrow down the specific issue you're facing.

**Comment by SoyGabor** [comment] 2019-07-24 13:46
Thank you for the quick replies. So I had an issue with my environment variable, re-running export LOADER_PATH solved the problem! 

However I have another issue now, it seems that the event mapper connector has no connector to an event bus.

The OMAG platform gives me the following messages when it is loading the logical servers:

Wed Jul 24 13:00:03 UTC 2019 EgeriaMetadataServer1 OMRS-AUDIT-0030 The local repository outbound event manager is initializing
Wed Jul 24 13:00:05 UTC 2019 EgeriaMetadataServer1 OMRS-AUDIT-0024 The local repositorys event mapper connector {0} is ready to send and receive events
Wed Jul 24 13:00:05 UTC 2019 EgeriaMetadataServer1 OMRS-AUDIT-0022 The local repositorys event mapper connector {0} has no connector to an event bus

I did POST the following during config (first call):

POST http://localhost:32780/open-metadata/admin-services/users/egeria/servers/EgeriaMetadataServer1/event-bus?connectorProvider=org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider&topicURLRoot=OMRSTopic

##with payload:
{
"producer":
{
"bootstrap.servers":"localhost:9092",
"acks":"all",
"retries":"0",
"batch.size":"16384",
"linger.ms":"1",
"buffer.memory":"33554432",
"max.request.size":"10485760",
"key.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"value.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"kafka.omrs.topic.id":"testCohort"
},
"consumer":
{
"bootstrap.servers":"localhost:9092",
"zookeeper.session.timeout.ms":"400",
"zookeeper.sync.time.ms":"200",
"fetch.message.max.bytes":"10485760",
"max.partition.fetch.bytes":"10485760",
"key.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"value.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"kafka.omrs.topic.id":"testCohort"
}
}

I am trying to run two Apache Atlas instances and connect them through Egeria, the plan is to demonstrate metadata exchange between them once they are connected. 

I have two Apache Atlas instances running in two Docker containers and Egeria is installed on the host so I just run the "server-chassis-spring-1.1-SNAPSHOT.jar" file from the folder where it's located. All of these are on a single host.

Thank you

**Comment by cmgrote** [comment] 2019-07-24 14:39
I'll need to double-check in my own environment, but I suspect the message you're seeing about the event bus may not actually be a problem (I still need to figure out what it's being output as such).  The main thing you'd want to check to confirm whether things are working or not is that changes in one of your Atlas environments are being published into your OMRS Kafka topic.

I suspect that given your setup your challenge is related to the port numbers and host names used by the Apache Atlas containers.  When running, they're both likely advertising their embedded Kafka servers as `localhost:9027`.  While you could use Docker's `-p 9027:9027` on one of the containers to make it accessible from your host itself at `localhost:9027`, the other would conflict (ie. try to use the same port on the Docker host).  You'll need to hack around in your `atlas-application.properties` file in each container to change the port on `atlas.kafka.listeners` and `atlas.kafka.advertised.listeners` to different ports within each container (eg. `9027` on one and `9028` on the other -- assuming these ports aren't used for something else already), map these to the same ports with `-p 9027:9027` on the first and `-p 9028:9028` on the second, and then configure each Egeria instance that refers to these with the respective (different) port for each container's embedded Kafka.

> I am trying to run two Apache Atlas instances and connect them through Egeria, the plan is to demonstrate metadata exchange between them once they are connected.

However, it's worth pointing out that regardless, at this point you won't be able to achieve what you're after anyway with the Atlas connector.  Per https://github.com/odpi/egeria-connector-apache-atlas/issues/4 there are some blocking gaps in Apache Atlas's support for certain concepts that prevent the connector from being anything more than a read-only connector at this point -- meaning that it won't be possible to exchange Atlas-to-Atlas (at least not yet).

The best you could likely do is to have your two Atlas environment exchange with a separate Egeria instance (eg. with its own local graph repository back-end).  The Egeria instance would then be able to consolidate the information from the two Atlas environments.

**Comment by SoyGabor** [comment] 2019-08-20 16:17
Hi! 
So I have been experimenting more, I have tried what you suggested, i.e. connecting Atlas and an in-memory repo to a cohort and trying to see if I can retrieve glossary items saved to Atlas by querying the other server in the cohort (i.e. the in-memory repository). I had some success but couldn't achieve what I wanted see more details below:

I created two logical servers on the OMAG platform, one for Atlas and one for the in-memory repo, and they seem to be working because they start without error and when I save a glossary item to the in-memory repo it is saved, and I can retrieve it by sending a GET request. After saving I also get a message on the command line (where the OMAG platform is running) that the logical server connected to Atlas tried to save this glossary item into Atlas but it failed (as expected). 

I realised that when I query (GET request) the logical server connected to Atlas for the glossary item I just saved to the in-memory repo, I actually get a response with my glossary item in it. 
The glossary item GUID is the same as the one saved in the in-memory repo. I suppose this is not a copy but the original? I thought querying the logical server in this case wouldn't be the same as a 'federated query' so I thought if I get a glossary item back that would have a different GUID? 

However, the main problem is that when I log into Atlas and save a new Glossary item in the UI, it doesn't have any effect on the cohort, no messages on the command line and nothing passed to the in-memory repo.
Do you have any ideas what may be the issue, here? Something is perhaps set up incorrectly around the Atlas event mapper or the Atlas topics? 
I am running an Atlas image called rokku-dev (ING) and Kafka and Zookeeper images externally to Atlas. I am trying to use the same Zookeeper and Kafka for the Egeria event bus and for those topics Atlas needs on its own.

Thank you
Gabor

**Comment by cmgrote** [comment] 2019-08-20 20:08
> However, the main problem is that when I log into Atlas and save a new Glossary item in the UI, it doesn't have any effect on the cohort, no messages on the command line and nothing passed to the in-memory repo.

Hi Gabor -- yes, this is unfortunately a known issue (with Atlas), specifically with Glossary-related entities (like terms).  See: https://github.com/odpi/egeria-connector-apache-atlas/issues/3 (and more specifically: https://issues.apache.org/jira/browse/ATLAS-3312).

You can also see this for yourself if you look at the `ATLAS_ENTITIES` topic that Atlas itself manages with its own entity notifications -- you should see notifications there for any non-Glossary entities (and relationships), but nothing for Glossary-related entities.

Please feel free to comment on the Atlas JIRA with the importance of this for you, as it's up to Atlas to create notifications on changes to Glossary-related entities before anything else (like Egeria) can pick up and translate them.

**Comment by cmgrote** [comment] 2019-09-24 12:18
I'll close this issue, given that the root cause is already tracked via other issues (which will still link back to this as well for broader context of impact).

**Closed by cmgrote** 2019-09-24 12:18 UTC
